- name: Store known hosts of 'all' the hosts in the inventory file
  hosts: localhost
  connection: local

  vars:
    ssh_targets: "{{ groups['all'] }}"
    ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"

  tasks:
    - name: For each host, scan for its ssh public key
      ansible.builtin.shell: "ssh-keyscan -T 10 {{ item }},`dig +short {{ item }}`"
      with_items: "{{ ssh_targets }}"
      register: ssh_known_host_results
      ignore_errors: true
      changed_when: false

    - name: Add/update the public key in the '{{ ssh_known_hosts_file }}'
      ansible.builtin.known_hosts:
        name: "{{ item.item }}"
        key: "{{ item.stdout }}"
        path: "{{ ssh_known_hosts_file }}"
      with_items: "{{ ssh_known_host_results.results }}"