version: "3.8"

networks:

  default:

services:

  main:
    image: com.gft.devops-event.ansible-demo-1.infrastructure.ansible-host:1.0.0
    container_name: main
    hostname: main
    stop_grace_period: 1s
    command: sleep 999999
    networks:
      - default
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    labels:
      CUSTOMER: com.gft.devops-event
      PROJECT: com.gft.devops-event.ansible-demo-1
      MODULE: infrastructure
      COMPONENT: ansible-host
      NAME: main
      SIGNATURE: com.gft.devops-event.ansible-demo-1.infrastructure.ansible-host.main
      VERSION: 1.0.0
    build:
      context: ./images/main
      dockerfile: Dockerfile
      labels:
        CUSTOMER: com.gft.devops-event
        PROJECT: com.gft.devops-event.ansible-demo-1
        MODULE: infrastructure
        COMPONENT: ansible-host
        NAME: main
        SIGNATURE: com.gft.devops-event.ansible-demo-1.infrastructure.ansible-host.main
        VERSION: 1.0.0

  worker_1:
    image: com.gft.devops-event.ansible-demo-1.app.worker.1:1.0.0
    container_name: worker_1
    hostname: worker_1
    stop_grace_period: 1s
    networks:
      - default
    labels:
      CUSTOMER: com.gft.devops-event
      PROJECT: com.gft.devops-event.ansible-demo-1
      MODULE: app
      COMPONENT: worker
      NAME: worker_1
      SIGNATURE: com.gft.devops-event.ansible-demo-1.app.worker.1
      VERSION: 1.0.0
    build:
      context: ./images/worker_1
      dockerfile: Dockerfile
      labels:
        CUSTOMER: com.gft.devops-event
        PROJECT: com.gft.devops-event.ansible-demo-1
        MODULE: app
        COMPONENT: worker
        NAME: worker_1
        SIGNATURE: com.gft.devops-event.ansible-demo-1.app.worker.1
        VERSION: 1.0.0

  worker_2:
    image: com.gft.devops-event.ansible-demo-1.app.worker.2:1.0.0
    container_name: worker_2
    hostname: worker_2
    stop_grace_period: 1s
    networks:
      - default
    labels:
      CUSTOMER: com.gft.devops-event
      PROJECT: com.gft.devops-event.ansible-demo-1
      MODULE: app
      COMPONENT: worker
      NAME: worker_2
      SIGNATURE: com.gft.devops-event.ansible-demo-1.app.worker.2
      VERSION: 1.0.0
    build:
      context: ./images/worker_2 
      dockerfile: Dockerfile
      labels:
        CUSTOMER: com.gft.devops-event
        PROJECT: com.gft.devops-event.ansible-demo-1
        MODULE: app
        COMPONENT: worker
        NAME: worker_2
        SIGNATURE: com.gft.devops-event.ansible-demo-1.app.worker.2
        VERSION: 1.0.0

  worker_3:
    image: com.gft.devops-event.ansible-demo-1.app.worker.3:1.0.0
    stop_grace_period: 1s
    networks:
      - default
    deploy:
      mode: replicated
      endpoint_mode: dnsrr
      replicas: 2
      labels:
        CUSTOMER: com.gft.devops-event
        PROJECT: com.gft.devops-event.ansible-demo-1
        MODULE: app
        COMPONENT: worker
        NAME: worker_3
        SIGNATURE: com.gft.devops-event.ansible-demo-1.app.worker.3
        VERSION: 1.0.0
    build:
      context: ./images/worker_3
      dockerfile: Dockerfile
      labels:
        CUSTOMER: com.gft.devops-event
        PROJECT: com.gft.devops-event.ansible-demo-1
        MODULE: app
        COMPONENT: worker
        NAME: worker_3
        SIGNATURE: com.gft.devops-event.ansible-demo-1.app.worker.3
        VERSION: 1.0.0

  database:
    image: com.gft.devops-event.ansible-demo-1.app.database.postgresql:1.0.0
    container_name: database
    hostname: database
    stop_grace_period: 1s
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGDATA=/data
    networks:
      - default
    labels:
      CUSTOMER: com.gft.devops-event
      PROJECT: com.gft.devops-event.ansible-demo-1
      MODULE: app
      COMPONENT: database
      NAME: database
      SIGNATURE: com.gft.devops-event.ansible-demo-1.app.database.postgresql
      VERSION: 1.0.0
    build:
      context: ./images/database
      dockerfile: Dockerfile
      labels:
        CUSTOMER: com.gft.devops-event
        PROJECT: com.gft.devops-event.ansible-demo-1
        MODULE: app
        COMPONENT: database
        NAME: postgresql
        SIGNATURE: com.gft.devops-event.ansible-demo-1.app.database.postgresql
        VERSION: 1.0.0
